# Site settings
title: reneVolution blog
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://joshgerdes.com/jekyll-uno' 
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'René Calles'
  #email: josh@joshgerdes.com
  #twitter_username: joshgerdes
  #facebook_username: joshgerdes
  github_username: ReneVolution
  #linkedin_username:  joshgerdes

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
