# Site settings
title: René Calles
description: 'Developer, Media Enthusiast and Fisherman'
url: 'http://renevolution.com' 
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'renevolutioncom'

author:
  name: 'René Calles'
  email: info@renevolution.com
  twitter_username: renecalles
  #facebook_username: joshgerdes
  github_username: ReneVolution
  linkedin_username: rené-calles-64188340

# Build settings
destination: _site
paginate: 10
paginate_path: "/blog/page/:num"
#permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
